MODEL  = src/main/java/com/cat_back/model
MAPPER = src/main/java/com/cat_back/mapper
XML    = src/main/resources/mapper
clean:
	rm $(MODEL)/Cargo.java $(MODEL)/CargoExample.java 
	rm $(MODEL)/Order.java $(MODEL)/OrderExample.java 
	rm $(MODEL)/Store.java $(MODEL)/StoreExample.java 
	rm $(MODEL)/User.java  $(MODEL)/UserExample.java
	rm $(MAPPER)/*
	rm $(XML)/*
